### ISSUE TITLE
Classe Restaurante

### ISSUE THREAD

**Issue by arthurcuri** [DisciplinasProgramacao/lpm-projeto2024-1-advanced-group#9]
@EduardoPalharesRealePereira  Implementar a classe do restaurante e testar. Caso necessite de outras classes para o teste, você pode fazer uma implementação "fake", mas lembre-se de só subir para o repositório as classes da sua tarefa.

**Comment by joaocaram** [comment]
@EduardoPalharesRealePereira A classe Restaurante tem seríssimos problemas de modularidade. Readequar a classe de acordo com as orientações da aula.
